
export const CATEGORIES = [
    "All",
    "Frontend",
    "Backend",
    "Full-Stack"
];

export const PROJECTS = [
    {
        id: 1,
        title: "MicroServices Platform",
        description:
            "Enterprise-grade microservices architecture with event-driven design patterns and distributed tracing.",
        longDescription:
            "Plataforma de microservicios empresarial construida con principios de Domain-Driven Design (DDD) y arquitectura orientada a eventos. Incluye monitoreo distribuido, service mesh con Istio, y gestión centralizada de configuración.",
        tags: ["DDD", "Microservices", "Node.js", "Docker"],
        category: "Backend",
        image: "/microservices-architecture-dashboard.jpg",
        images: ["/microservices-dashboard-metrics.jpg", "/distributed-tracing-visualization.png"],
        features: [
            "Arquitectura basada en eventos con Kafka",
            "Service discovery con Consul",
            "API Gateway centralizado con autenticación JWT",
            "Monitoreo y trazabilidad distribuida con Jaeger",
            "Circuit breaker y retry patterns",
            "Despliegue automatizado con CI/CD",
        ],
        techStack: [
            { name: "Node.js + Express", description: "Backend de microservicios con Express y TypeScript" },
            { name: "Kafka", description: "Message broker para comunicación asíncrona" },
            { name: "Docker + Kubernetes", description: "Containerización y orquestación" },
            { name: "PostgreSQL + Redis", description: "Bases de datos relacionales y caching" },
        ],
        demo: "https://example.com",
        github: "https://github.com",
        hasDetails: true,
    },
    {
        id: 2,
        title: "Real-time Analytics Dashboard",
        description: "Interactive analytics platform with WebSocket real-time updates and advanced data visualization.",
        longDescription:
            "Dashboard interactivo de analytics con actualizaciones en tiempo real mediante WebSockets. Incluye visualizaciones avanzadas con D3.js, filtros dinámicos y exportación de reportes personalizados.",
        tags: ["React", "TypeScript", "Next.js", "Websockets"],
        category: "Frontend",
        image: "/analytics-dashboard-charts.jpg",
        images: ["/data-visualization-charts-graphs.jpg", "/real-time-dashboard-metrics.jpg"],
        features: [
            "Actualizaciones en tiempo real con WebSockets",
            "Visualizaciones interactivas con D3.js y Recharts",
            "Sistema de filtros y agregaciones dinámicas",
            "Exportación de reportes en PDF y Excel",
            "Dashboard personalizable con drag-and-drop",
            "Modo offline con sincronización automática",
        ],
        techStack: [
            { name: "Next.js 16 + React", description: "Framework frontend con Server Components" },
            { name: "TanStack Query", description: "Gestión de estado y caché de datos" },
            { name: "D3.js + Recharts", description: "Visualización de datos avanzada" },
            { name: "WebSocket + Socket.io", description: "Comunicación bidireccional en tiempo real" },
        ],
        demo: "https://example.com",
        github: "https://github.com",
        hasDetails: true,
    },
    {
        id: 3,
        title: "E-commerce Platform",
        description: "Full-stack e-commerce solution with payment integration, inventory management, and admin dashboard.",
        tags: ["Full-Stack", "Next.js", "Stripe", "PostgreSQL"],
        category: "Full-Stack",
        image: "/ecommerce-product-page.jpg",
        demo: "https://example.com",
        github: "https://github.com",
        hasDetails: false,
    },
    {
        id: 4,
        title: "API Gateway & Auth Service",
        description: "Centralized authentication and API gateway with role-based access control and OAuth integration.",
        tags: ["Security", "Auth", "Node.js", "JWT"],
        category: "Backend",
        image: "/security-authentication-system.jpg",
        demo: "https://example.com",
        github: "https://github.com",
        hasDetails: false,
    },
    {
        id: 5,
        title: "Component Design System",
        description: "Comprehensive design system with 50+ components, documentation, and Figma integration.",
        tags: ["Design System", "React", "Storybook", "Tailwind"],
        category: "Frontend",
        image: "/design-system-components.jpg",
        demo: "https://example.com",
        github: "https://github.com",
        hasDetails: false,
    },
    {
        id: 6,
        title: "Content Management System",
        description: "Headless CMS with markdown support, version control, and multi-environment publishing.",
        tags: ["CMS", "Next.js", "Database", "API"],
        category: "Full-Stack",
        image: "/content-management-interface.jpg",
        demo: "https://example.com",
        github: "https://github.com",
        hasDetails: false,
    },
];
